import { defineConfig } from 'vite';

export default defineConfig({
  appType: 'mpa',
  base: './',
  build: {
    chunkSizeWarningLimit: 1200,
    rollupOptions: {
      input: {
        main: 'index.html',
        now: 'now.html',
        morning: 'morning.html',
        walk: 'walk.html',
        boxes: 'boxes.html',
        builder: 'builder.html',
        seasons: 'seasons.html',
        journal: 'journal.html',
        zone: 'zone.html',
        passport: 'passport.html',
        join: 'join.html',
        loyalty: 'loyalty.html',
        foodcourt: 'foodcourt.html',
        search: 'search.html',
        faq: 'faq.html',
        sitemap: 'sitemap.html',
        stories: 'stories.html',
        journalFarm: 'journal-farm.html',
        press: 'press.html',
        catalog: 'catalog.html',
        product: 'product.html',
        farmers: 'farmers.html',
        farmer: 'farmer.html',
        events: 'events.html',
        event: 'event.html',
        blog: 'blog.html',
        article: 'article.html',
        recipes: 'recipes.html',
        recipe: 'recipe.html',
        partners: 'partners.html',
        about: 'about.html',
        guests: 'guests.html',
        contacts: 'contacts.html',
        delivery: 'delivery.html',
        cart: 'cart.html',
        checkout: 'checkout.html',
        orderSuccess: 'order-success.html',
        privacy: 'privacy.html',
        terms: 'terms.html',
        map: 'map.html',
        notFound: '404.html',
      },
    },
  },
});
